#ifndef UNIQUEASSET3_GLOBAL_H
#define UNIQUEASSET3_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNIQUEASSET3_LIBRARY)
#define UNIQUEASSET3_EXPORT Q_DECL_EXPORT
#else
#define UNIQUEASSET3_EXPORT Q_DECL_IMPORT
#endif

#endif // UNIQUEASSET3_GLOBAL_H
