#ifndef UNIQUEASSET1_GLOBAL_H
#define UNIQUEASSET1_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNIQUEASSET1_LIBRARY)
#define UNIQUEASSET1_EXPORT Q_DECL_EXPORT
#else
#define UNIQUEASSET1_EXPORT Q_DECL_IMPORT
#endif

#endif // UNIQUEASSET1_GLOBAL_H
