#ifndef UNIQUEASSET4_GLOBAL_H
#define UNIQUEASSET4_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNIQUEASSET4_LIBRARY)
#define UNIQUEASSET4_EXPORT Q_DECL_EXPORT
#else
#define UNIQUEASSET4_EXPORT Q_DECL_IMPORT
#endif

#endif // UNIQUEASSET4_GLOBAL_H
