
list(APPEND HEADERS UniqueAsset4/tst_uniqueasset4.h)
list(APPEND SOURCES UniqueAsset4/tst_uniqueasset4.cpp)

if(MSVC)
    if(CMAKE_BUILD_TYPE STREQUAL "Release")
        list(APPEND LIBS -L${CMAKE_CURRENT_BINARY_DIR}/../UniqueAsset4/release/ -lUniqueAsset4)
        list(APPEND ASSETS_LIB_PATH ${CMAKE_CURRENT_BINARY_DIR}/../UniqueAsset4/release/libUniqueAsset4.dll)
    else()
        list(APPEND LIBS -L${CMAKE_CURRENT_BINARY_DIR}/../UniqueAsset4/debug/ -lUniqueAsset4)
        list(APPEND ASSETS_LIB_PATH ${CMAKE_CURRENT_BINARY_DIR}/../UniqueAsset4/debug/libUniqueAsset4.dll)
    endif()
else()
    list(APPEND LIBS -L${CMAKE_CURRENT_BINARY_DIR}/../UniqueAsset4/ -lUniqueAsset4)
    list(APPEND ASSETS_LIB_PATH ${CMAKE_CURRENT_BINARY_DIR}/../UniqueAsset4/libUniqueAsset4.dll)
endif()

list(APPEND DEFINES -DUAsset4)
list(APPEND ASSETS_HEADER_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../UniqueAsset4)
list(APPEND Dependencies UniqueAsset4)
