// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: productline_api.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_productline_5fapi_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_productline_5fapi_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_productline_5fapi_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_productline_5fapi_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_productline_5fapi_2eproto;
namespace productline {
class CallFunctionRequest;
struct CallFunctionRequestDefaultTypeInternal;
extern CallFunctionRequestDefaultTypeInternal _CallFunctionRequest_default_instance_;
class CallFunctionResponse;
struct CallFunctionResponseDefaultTypeInternal;
extern CallFunctionResponseDefaultTypeInternal _CallFunctionResponse_default_instance_;
class GetInstanceRequest;
struct GetInstanceRequestDefaultTypeInternal;
extern GetInstanceRequestDefaultTypeInternal _GetInstanceRequest_default_instance_;
class GetInstanceResponse;
struct GetInstanceResponseDefaultTypeInternal;
extern GetInstanceResponseDefaultTypeInternal _GetInstanceResponse_default_instance_;
class InsertInstanceRequest;
struct InsertInstanceRequestDefaultTypeInternal;
extern InsertInstanceRequestDefaultTypeInternal _InsertInstanceRequest_default_instance_;
class InsertInstanceResponse;
struct InsertInstanceResponseDefaultTypeInternal;
extern InsertInstanceResponseDefaultTypeInternal _InsertInstanceResponse_default_instance_;
}  // namespace productline
PROTOBUF_NAMESPACE_OPEN
template<> ::productline::CallFunctionRequest* Arena::CreateMaybeMessage<::productline::CallFunctionRequest>(Arena*);
template<> ::productline::CallFunctionResponse* Arena::CreateMaybeMessage<::productline::CallFunctionResponse>(Arena*);
template<> ::productline::GetInstanceRequest* Arena::CreateMaybeMessage<::productline::GetInstanceRequest>(Arena*);
template<> ::productline::GetInstanceResponse* Arena::CreateMaybeMessage<::productline::GetInstanceResponse>(Arena*);
template<> ::productline::InsertInstanceRequest* Arena::CreateMaybeMessage<::productline::InsertInstanceRequest>(Arena*);
template<> ::productline::InsertInstanceResponse* Arena::CreateMaybeMessage<::productline::InsertInstanceResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace productline {

// ===================================================================

class CallFunctionRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:productline.CallFunctionRequest) */ {
 public:
  inline CallFunctionRequest() : CallFunctionRequest(nullptr) {}
  ~CallFunctionRequest() override;
  explicit PROTOBUF_CONSTEXPR CallFunctionRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CallFunctionRequest(const CallFunctionRequest& from);
  CallFunctionRequest(CallFunctionRequest&& from) noexcept
    : CallFunctionRequest() {
    *this = ::std::move(from);
  }

  inline CallFunctionRequest& operator=(const CallFunctionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CallFunctionRequest& operator=(CallFunctionRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CallFunctionRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const CallFunctionRequest* internal_default_instance() {
    return reinterpret_cast<const CallFunctionRequest*>(
               &_CallFunctionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CallFunctionRequest& a, CallFunctionRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(CallFunctionRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CallFunctionRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CallFunctionRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CallFunctionRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CallFunctionRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CallFunctionRequest& from) {
    CallFunctionRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CallFunctionRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "productline.CallFunctionRequest";
  }
  protected:
  explicit CallFunctionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFunctionNameFieldNumber = 2,
    kParamsJsonFieldNumber = 3,
    kInstanceIdFieldNumber = 1,
  };
  // string function_name = 2;
  void clear_function_name();
  const std::string& function_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_function_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_function_name();
  PROTOBUF_NODISCARD std::string* release_function_name();
  void set_allocated_function_name(std::string* function_name);
  private:
  const std::string& _internal_function_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_function_name(const std::string& value);
  std::string* _internal_mutable_function_name();
  public:

  // string params_json = 3;
  void clear_params_json();
  const std::string& params_json() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_params_json(ArgT0&& arg0, ArgT... args);
  std::string* mutable_params_json();
  PROTOBUF_NODISCARD std::string* release_params_json();
  void set_allocated_params_json(std::string* params_json);
  private:
  const std::string& _internal_params_json() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_params_json(const std::string& value);
  std::string* _internal_mutable_params_json();
  public:

  // uint64 instance_id = 1;
  void clear_instance_id();
  uint64_t instance_id() const;
  void set_instance_id(uint64_t value);
  private:
  uint64_t _internal_instance_id() const;
  void _internal_set_instance_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:productline.CallFunctionRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr function_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr params_json_;
    uint64_t instance_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_productline_5fapi_2eproto;
};
// -------------------------------------------------------------------

class CallFunctionResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:productline.CallFunctionResponse) */ {
 public:
  inline CallFunctionResponse() : CallFunctionResponse(nullptr) {}
  ~CallFunctionResponse() override;
  explicit PROTOBUF_CONSTEXPR CallFunctionResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CallFunctionResponse(const CallFunctionResponse& from);
  CallFunctionResponse(CallFunctionResponse&& from) noexcept
    : CallFunctionResponse() {
    *this = ::std::move(from);
  }

  inline CallFunctionResponse& operator=(const CallFunctionResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CallFunctionResponse& operator=(CallFunctionResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CallFunctionResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const CallFunctionResponse* internal_default_instance() {
    return reinterpret_cast<const CallFunctionResponse*>(
               &_CallFunctionResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CallFunctionResponse& a, CallFunctionResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(CallFunctionResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CallFunctionResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CallFunctionResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CallFunctionResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CallFunctionResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CallFunctionResponse& from) {
    CallFunctionResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CallFunctionResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "productline.CallFunctionResponse";
  }
  protected:
  explicit CallFunctionResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultJsonFieldNumber = 1,
    kErrorFieldNumber = 2,
  };
  // string result_json = 1;
  void clear_result_json();
  const std::string& result_json() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_result_json(ArgT0&& arg0, ArgT... args);
  std::string* mutable_result_json();
  PROTOBUF_NODISCARD std::string* release_result_json();
  void set_allocated_result_json(std::string* result_json);
  private:
  const std::string& _internal_result_json() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_result_json(const std::string& value);
  std::string* _internal_mutable_result_json();
  public:

  // string error = 2;
  void clear_error();
  const std::string& error() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error();
  PROTOBUF_NODISCARD std::string* release_error();
  void set_allocated_error(std::string* error);
  private:
  const std::string& _internal_error() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error(const std::string& value);
  std::string* _internal_mutable_error();
  public:

  // @@protoc_insertion_point(class_scope:productline.CallFunctionResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr result_json_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_productline_5fapi_2eproto;
};
// -------------------------------------------------------------------

class GetInstanceRequest final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:productline.GetInstanceRequest) */ {
 public:
  inline GetInstanceRequest() : GetInstanceRequest(nullptr) {}
  explicit PROTOBUF_CONSTEXPR GetInstanceRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetInstanceRequest(const GetInstanceRequest& from);
  GetInstanceRequest(GetInstanceRequest&& from) noexcept
    : GetInstanceRequest() {
    *this = ::std::move(from);
  }

  inline GetInstanceRequest& operator=(const GetInstanceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetInstanceRequest& operator=(GetInstanceRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetInstanceRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetInstanceRequest* internal_default_instance() {
    return reinterpret_cast<const GetInstanceRequest*>(
               &_GetInstanceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetInstanceRequest& a, GetInstanceRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetInstanceRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetInstanceRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetInstanceRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetInstanceRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const GetInstanceRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const GetInstanceRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "productline.GetInstanceRequest";
  }
  protected:
  explicit GetInstanceRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:productline.GetInstanceRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_productline_5fapi_2eproto;
};
// -------------------------------------------------------------------

class GetInstanceResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:productline.GetInstanceResponse) */ {
 public:
  inline GetInstanceResponse() : GetInstanceResponse(nullptr) {}
  ~GetInstanceResponse() override;
  explicit PROTOBUF_CONSTEXPR GetInstanceResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetInstanceResponse(const GetInstanceResponse& from);
  GetInstanceResponse(GetInstanceResponse&& from) noexcept
    : GetInstanceResponse() {
    *this = ::std::move(from);
  }

  inline GetInstanceResponse& operator=(const GetInstanceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetInstanceResponse& operator=(GetInstanceResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetInstanceResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetInstanceResponse* internal_default_instance() {
    return reinterpret_cast<const GetInstanceResponse*>(
               &_GetInstanceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(GetInstanceResponse& a, GetInstanceResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetInstanceResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetInstanceResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetInstanceResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetInstanceResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetInstanceResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetInstanceResponse& from) {
    GetInstanceResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetInstanceResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "productline.GetInstanceResponse";
  }
  protected:
  explicit GetInstanceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorFieldNumber = 2,
    kInstanceIdFieldNumber = 1,
  };
  // string error = 2;
  void clear_error();
  const std::string& error() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error();
  PROTOBUF_NODISCARD std::string* release_error();
  void set_allocated_error(std::string* error);
  private:
  const std::string& _internal_error() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error(const std::string& value);
  std::string* _internal_mutable_error();
  public:

  // uint64 instance_id = 1;
  void clear_instance_id();
  uint64_t instance_id() const;
  void set_instance_id(uint64_t value);
  private:
  uint64_t _internal_instance_id() const;
  void _internal_set_instance_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:productline.GetInstanceResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_;
    uint64_t instance_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_productline_5fapi_2eproto;
};
// -------------------------------------------------------------------

class InsertInstanceRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:productline.InsertInstanceRequest) */ {
 public:
  inline InsertInstanceRequest() : InsertInstanceRequest(nullptr) {}
  ~InsertInstanceRequest() override;
  explicit PROTOBUF_CONSTEXPR InsertInstanceRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InsertInstanceRequest(const InsertInstanceRequest& from);
  InsertInstanceRequest(InsertInstanceRequest&& from) noexcept
    : InsertInstanceRequest() {
    *this = ::std::move(from);
  }

  inline InsertInstanceRequest& operator=(const InsertInstanceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline InsertInstanceRequest& operator=(InsertInstanceRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InsertInstanceRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const InsertInstanceRequest* internal_default_instance() {
    return reinterpret_cast<const InsertInstanceRequest*>(
               &_InsertInstanceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(InsertInstanceRequest& a, InsertInstanceRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(InsertInstanceRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InsertInstanceRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InsertInstanceRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InsertInstanceRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InsertInstanceRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InsertInstanceRequest& from) {
    InsertInstanceRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InsertInstanceRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "productline.InsertInstanceRequest";
  }
  protected:
  explicit InsertInstanceRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInstanceTypeFieldNumber = 2,
    kInstanceIdFieldNumber = 1,
  };
  // string instance_type = 2;
  void clear_instance_type();
  const std::string& instance_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_instance_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_instance_type();
  PROTOBUF_NODISCARD std::string* release_instance_type();
  void set_allocated_instance_type(std::string* instance_type);
  private:
  const std::string& _internal_instance_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_instance_type(const std::string& value);
  std::string* _internal_mutable_instance_type();
  public:

  // uint64 instance_id = 1;
  void clear_instance_id();
  uint64_t instance_id() const;
  void set_instance_id(uint64_t value);
  private:
  uint64_t _internal_instance_id() const;
  void _internal_set_instance_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:productline.InsertInstanceRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr instance_type_;
    uint64_t instance_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_productline_5fapi_2eproto;
};
// -------------------------------------------------------------------

class InsertInstanceResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:productline.InsertInstanceResponse) */ {
 public:
  inline InsertInstanceResponse() : InsertInstanceResponse(nullptr) {}
  ~InsertInstanceResponse() override;
  explicit PROTOBUF_CONSTEXPR InsertInstanceResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InsertInstanceResponse(const InsertInstanceResponse& from);
  InsertInstanceResponse(InsertInstanceResponse&& from) noexcept
    : InsertInstanceResponse() {
    *this = ::std::move(from);
  }

  inline InsertInstanceResponse& operator=(const InsertInstanceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline InsertInstanceResponse& operator=(InsertInstanceResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InsertInstanceResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const InsertInstanceResponse* internal_default_instance() {
    return reinterpret_cast<const InsertInstanceResponse*>(
               &_InsertInstanceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(InsertInstanceResponse& a, InsertInstanceResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(InsertInstanceResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InsertInstanceResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InsertInstanceResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InsertInstanceResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InsertInstanceResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InsertInstanceResponse& from) {
    InsertInstanceResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InsertInstanceResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "productline.InsertInstanceResponse";
  }
  protected:
  explicit InsertInstanceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // string error = 2;
  void clear_error();
  const std::string& error() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error();
  PROTOBUF_NODISCARD std::string* release_error();
  void set_allocated_error(std::string* error);
  private:
  const std::string& _internal_error() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error(const std::string& value);
  std::string* _internal_mutable_error();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:productline.InsertInstanceResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_productline_5fapi_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CallFunctionRequest

// uint64 instance_id = 1;
inline void CallFunctionRequest::clear_instance_id() {
  _impl_.instance_id_ = uint64_t{0u};
}
inline uint64_t CallFunctionRequest::_internal_instance_id() const {
  return _impl_.instance_id_;
}
inline uint64_t CallFunctionRequest::instance_id() const {
  // @@protoc_insertion_point(field_get:productline.CallFunctionRequest.instance_id)
  return _internal_instance_id();
}
inline void CallFunctionRequest::_internal_set_instance_id(uint64_t value) {
  
  _impl_.instance_id_ = value;
}
inline void CallFunctionRequest::set_instance_id(uint64_t value) {
  _internal_set_instance_id(value);
  // @@protoc_insertion_point(field_set:productline.CallFunctionRequest.instance_id)
}

// string function_name = 2;
inline void CallFunctionRequest::clear_function_name() {
  _impl_.function_name_.ClearToEmpty();
}
inline const std::string& CallFunctionRequest::function_name() const {
  // @@protoc_insertion_point(field_get:productline.CallFunctionRequest.function_name)
  return _internal_function_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CallFunctionRequest::set_function_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.function_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:productline.CallFunctionRequest.function_name)
}
inline std::string* CallFunctionRequest::mutable_function_name() {
  std::string* _s = _internal_mutable_function_name();
  // @@protoc_insertion_point(field_mutable:productline.CallFunctionRequest.function_name)
  return _s;
}
inline const std::string& CallFunctionRequest::_internal_function_name() const {
  return _impl_.function_name_.Get();
}
inline void CallFunctionRequest::_internal_set_function_name(const std::string& value) {
  
  _impl_.function_name_.Set(value, GetArenaForAllocation());
}
inline std::string* CallFunctionRequest::_internal_mutable_function_name() {
  
  return _impl_.function_name_.Mutable(GetArenaForAllocation());
}
inline std::string* CallFunctionRequest::release_function_name() {
  // @@protoc_insertion_point(field_release:productline.CallFunctionRequest.function_name)
  return _impl_.function_name_.Release();
}
inline void CallFunctionRequest::set_allocated_function_name(std::string* function_name) {
  if (function_name != nullptr) {
    
  } else {
    
  }
  _impl_.function_name_.SetAllocated(function_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.function_name_.IsDefault()) {
    _impl_.function_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:productline.CallFunctionRequest.function_name)
}

// string params_json = 3;
inline void CallFunctionRequest::clear_params_json() {
  _impl_.params_json_.ClearToEmpty();
}
inline const std::string& CallFunctionRequest::params_json() const {
  // @@protoc_insertion_point(field_get:productline.CallFunctionRequest.params_json)
  return _internal_params_json();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CallFunctionRequest::set_params_json(ArgT0&& arg0, ArgT... args) {
 
 _impl_.params_json_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:productline.CallFunctionRequest.params_json)
}
inline std::string* CallFunctionRequest::mutable_params_json() {
  std::string* _s = _internal_mutable_params_json();
  // @@protoc_insertion_point(field_mutable:productline.CallFunctionRequest.params_json)
  return _s;
}
inline const std::string& CallFunctionRequest::_internal_params_json() const {
  return _impl_.params_json_.Get();
}
inline void CallFunctionRequest::_internal_set_params_json(const std::string& value) {
  
  _impl_.params_json_.Set(value, GetArenaForAllocation());
}
inline std::string* CallFunctionRequest::_internal_mutable_params_json() {
  
  return _impl_.params_json_.Mutable(GetArenaForAllocation());
}
inline std::string* CallFunctionRequest::release_params_json() {
  // @@protoc_insertion_point(field_release:productline.CallFunctionRequest.params_json)
  return _impl_.params_json_.Release();
}
inline void CallFunctionRequest::set_allocated_params_json(std::string* params_json) {
  if (params_json != nullptr) {
    
  } else {
    
  }
  _impl_.params_json_.SetAllocated(params_json, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.params_json_.IsDefault()) {
    _impl_.params_json_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:productline.CallFunctionRequest.params_json)
}

// -------------------------------------------------------------------

// CallFunctionResponse

// string result_json = 1;
inline void CallFunctionResponse::clear_result_json() {
  _impl_.result_json_.ClearToEmpty();
}
inline const std::string& CallFunctionResponse::result_json() const {
  // @@protoc_insertion_point(field_get:productline.CallFunctionResponse.result_json)
  return _internal_result_json();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CallFunctionResponse::set_result_json(ArgT0&& arg0, ArgT... args) {
 
 _impl_.result_json_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:productline.CallFunctionResponse.result_json)
}
inline std::string* CallFunctionResponse::mutable_result_json() {
  std::string* _s = _internal_mutable_result_json();
  // @@protoc_insertion_point(field_mutable:productline.CallFunctionResponse.result_json)
  return _s;
}
inline const std::string& CallFunctionResponse::_internal_result_json() const {
  return _impl_.result_json_.Get();
}
inline void CallFunctionResponse::_internal_set_result_json(const std::string& value) {
  
  _impl_.result_json_.Set(value, GetArenaForAllocation());
}
inline std::string* CallFunctionResponse::_internal_mutable_result_json() {
  
  return _impl_.result_json_.Mutable(GetArenaForAllocation());
}
inline std::string* CallFunctionResponse::release_result_json() {
  // @@protoc_insertion_point(field_release:productline.CallFunctionResponse.result_json)
  return _impl_.result_json_.Release();
}
inline void CallFunctionResponse::set_allocated_result_json(std::string* result_json) {
  if (result_json != nullptr) {
    
  } else {
    
  }
  _impl_.result_json_.SetAllocated(result_json, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.result_json_.IsDefault()) {
    _impl_.result_json_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:productline.CallFunctionResponse.result_json)
}

// string error = 2;
inline void CallFunctionResponse::clear_error() {
  _impl_.error_.ClearToEmpty();
}
inline const std::string& CallFunctionResponse::error() const {
  // @@protoc_insertion_point(field_get:productline.CallFunctionResponse.error)
  return _internal_error();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CallFunctionResponse::set_error(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:productline.CallFunctionResponse.error)
}
inline std::string* CallFunctionResponse::mutable_error() {
  std::string* _s = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:productline.CallFunctionResponse.error)
  return _s;
}
inline const std::string& CallFunctionResponse::_internal_error() const {
  return _impl_.error_.Get();
}
inline void CallFunctionResponse::_internal_set_error(const std::string& value) {
  
  _impl_.error_.Set(value, GetArenaForAllocation());
}
inline std::string* CallFunctionResponse::_internal_mutable_error() {
  
  return _impl_.error_.Mutable(GetArenaForAllocation());
}
inline std::string* CallFunctionResponse::release_error() {
  // @@protoc_insertion_point(field_release:productline.CallFunctionResponse.error)
  return _impl_.error_.Release();
}
inline void CallFunctionResponse::set_allocated_error(std::string* error) {
  if (error != nullptr) {
    
  } else {
    
  }
  _impl_.error_.SetAllocated(error, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_.IsDefault()) {
    _impl_.error_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:productline.CallFunctionResponse.error)
}

// -------------------------------------------------------------------

// GetInstanceRequest

// -------------------------------------------------------------------

// GetInstanceResponse

// uint64 instance_id = 1;
inline void GetInstanceResponse::clear_instance_id() {
  _impl_.instance_id_ = uint64_t{0u};
}
inline uint64_t GetInstanceResponse::_internal_instance_id() const {
  return _impl_.instance_id_;
}
inline uint64_t GetInstanceResponse::instance_id() const {
  // @@protoc_insertion_point(field_get:productline.GetInstanceResponse.instance_id)
  return _internal_instance_id();
}
inline void GetInstanceResponse::_internal_set_instance_id(uint64_t value) {
  
  _impl_.instance_id_ = value;
}
inline void GetInstanceResponse::set_instance_id(uint64_t value) {
  _internal_set_instance_id(value);
  // @@protoc_insertion_point(field_set:productline.GetInstanceResponse.instance_id)
}

// string error = 2;
inline void GetInstanceResponse::clear_error() {
  _impl_.error_.ClearToEmpty();
}
inline const std::string& GetInstanceResponse::error() const {
  // @@protoc_insertion_point(field_get:productline.GetInstanceResponse.error)
  return _internal_error();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetInstanceResponse::set_error(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:productline.GetInstanceResponse.error)
}
inline std::string* GetInstanceResponse::mutable_error() {
  std::string* _s = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:productline.GetInstanceResponse.error)
  return _s;
}
inline const std::string& GetInstanceResponse::_internal_error() const {
  return _impl_.error_.Get();
}
inline void GetInstanceResponse::_internal_set_error(const std::string& value) {
  
  _impl_.error_.Set(value, GetArenaForAllocation());
}
inline std::string* GetInstanceResponse::_internal_mutable_error() {
  
  return _impl_.error_.Mutable(GetArenaForAllocation());
}
inline std::string* GetInstanceResponse::release_error() {
  // @@protoc_insertion_point(field_release:productline.GetInstanceResponse.error)
  return _impl_.error_.Release();
}
inline void GetInstanceResponse::set_allocated_error(std::string* error) {
  if (error != nullptr) {
    
  } else {
    
  }
  _impl_.error_.SetAllocated(error, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_.IsDefault()) {
    _impl_.error_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:productline.GetInstanceResponse.error)
}

// -------------------------------------------------------------------

// InsertInstanceRequest

// uint64 instance_id = 1;
inline void InsertInstanceRequest::clear_instance_id() {
  _impl_.instance_id_ = uint64_t{0u};
}
inline uint64_t InsertInstanceRequest::_internal_instance_id() const {
  return _impl_.instance_id_;
}
inline uint64_t InsertInstanceRequest::instance_id() const {
  // @@protoc_insertion_point(field_get:productline.InsertInstanceRequest.instance_id)
  return _internal_instance_id();
}
inline void InsertInstanceRequest::_internal_set_instance_id(uint64_t value) {
  
  _impl_.instance_id_ = value;
}
inline void InsertInstanceRequest::set_instance_id(uint64_t value) {
  _internal_set_instance_id(value);
  // @@protoc_insertion_point(field_set:productline.InsertInstanceRequest.instance_id)
}

// string instance_type = 2;
inline void InsertInstanceRequest::clear_instance_type() {
  _impl_.instance_type_.ClearToEmpty();
}
inline const std::string& InsertInstanceRequest::instance_type() const {
  // @@protoc_insertion_point(field_get:productline.InsertInstanceRequest.instance_type)
  return _internal_instance_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void InsertInstanceRequest::set_instance_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.instance_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:productline.InsertInstanceRequest.instance_type)
}
inline std::string* InsertInstanceRequest::mutable_instance_type() {
  std::string* _s = _internal_mutable_instance_type();
  // @@protoc_insertion_point(field_mutable:productline.InsertInstanceRequest.instance_type)
  return _s;
}
inline const std::string& InsertInstanceRequest::_internal_instance_type() const {
  return _impl_.instance_type_.Get();
}
inline void InsertInstanceRequest::_internal_set_instance_type(const std::string& value) {
  
  _impl_.instance_type_.Set(value, GetArenaForAllocation());
}
inline std::string* InsertInstanceRequest::_internal_mutable_instance_type() {
  
  return _impl_.instance_type_.Mutable(GetArenaForAllocation());
}
inline std::string* InsertInstanceRequest::release_instance_type() {
  // @@protoc_insertion_point(field_release:productline.InsertInstanceRequest.instance_type)
  return _impl_.instance_type_.Release();
}
inline void InsertInstanceRequest::set_allocated_instance_type(std::string* instance_type) {
  if (instance_type != nullptr) {
    
  } else {
    
  }
  _impl_.instance_type_.SetAllocated(instance_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.instance_type_.IsDefault()) {
    _impl_.instance_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:productline.InsertInstanceRequest.instance_type)
}

// -------------------------------------------------------------------

// InsertInstanceResponse

// bool success = 1;
inline void InsertInstanceResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool InsertInstanceResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool InsertInstanceResponse::success() const {
  // @@protoc_insertion_point(field_get:productline.InsertInstanceResponse.success)
  return _internal_success();
}
inline void InsertInstanceResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void InsertInstanceResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:productline.InsertInstanceResponse.success)
}

// string error = 2;
inline void InsertInstanceResponse::clear_error() {
  _impl_.error_.ClearToEmpty();
}
inline const std::string& InsertInstanceResponse::error() const {
  // @@protoc_insertion_point(field_get:productline.InsertInstanceResponse.error)
  return _internal_error();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void InsertInstanceResponse::set_error(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:productline.InsertInstanceResponse.error)
}
inline std::string* InsertInstanceResponse::mutable_error() {
  std::string* _s = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:productline.InsertInstanceResponse.error)
  return _s;
}
inline const std::string& InsertInstanceResponse::_internal_error() const {
  return _impl_.error_.Get();
}
inline void InsertInstanceResponse::_internal_set_error(const std::string& value) {
  
  _impl_.error_.Set(value, GetArenaForAllocation());
}
inline std::string* InsertInstanceResponse::_internal_mutable_error() {
  
  return _impl_.error_.Mutable(GetArenaForAllocation());
}
inline std::string* InsertInstanceResponse::release_error() {
  // @@protoc_insertion_point(field_release:productline.InsertInstanceResponse.error)
  return _impl_.error_.Release();
}
inline void InsertInstanceResponse::set_allocated_error(std::string* error) {
  if (error != nullptr) {
    
  } else {
    
  }
  _impl_.error_.SetAllocated(error, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_.IsDefault()) {
    _impl_.error_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:productline.InsertInstanceResponse.error)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace productline

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_productline_5fapi_2eproto
