// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: productline_api.proto

#include "productline_api.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace productline {
PROTOBUF_CONSTEXPR CallFunctionRequest::CallFunctionRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.function_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.params_json_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.instance_id_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CallFunctionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CallFunctionRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CallFunctionRequestDefaultTypeInternal() {}
  union {
    CallFunctionRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CallFunctionRequestDefaultTypeInternal _CallFunctionRequest_default_instance_;
PROTOBUF_CONSTEXPR CallFunctionResponse::CallFunctionResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.result_json_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.error_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CallFunctionResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CallFunctionResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CallFunctionResponseDefaultTypeInternal() {}
  union {
    CallFunctionResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CallFunctionResponseDefaultTypeInternal _CallFunctionResponse_default_instance_;
PROTOBUF_CONSTEXPR GetInstanceRequest::GetInstanceRequest(
    ::_pbi::ConstantInitialized) {}
struct GetInstanceRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetInstanceRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetInstanceRequestDefaultTypeInternal() {}
  union {
    GetInstanceRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetInstanceRequestDefaultTypeInternal _GetInstanceRequest_default_instance_;
PROTOBUF_CONSTEXPR GetInstanceResponse::GetInstanceResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.error_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.instance_id_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetInstanceResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetInstanceResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetInstanceResponseDefaultTypeInternal() {}
  union {
    GetInstanceResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetInstanceResponseDefaultTypeInternal _GetInstanceResponse_default_instance_;
PROTOBUF_CONSTEXPR InsertInstanceRequest::InsertInstanceRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.instance_type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.instance_id_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InsertInstanceRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InsertInstanceRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InsertInstanceRequestDefaultTypeInternal() {}
  union {
    InsertInstanceRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InsertInstanceRequestDefaultTypeInternal _InsertInstanceRequest_default_instance_;
PROTOBUF_CONSTEXPR InsertInstanceResponse::InsertInstanceResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.error_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.success_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InsertInstanceResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InsertInstanceResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InsertInstanceResponseDefaultTypeInternal() {}
  union {
    InsertInstanceResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InsertInstanceResponseDefaultTypeInternal _InsertInstanceResponse_default_instance_;
}  // namespace productline
static ::_pb::Metadata file_level_metadata_productline_5fapi_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_productline_5fapi_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_productline_5fapi_2eproto = nullptr;

const uint32_t TableStruct_productline_5fapi_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::productline::CallFunctionRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::productline::CallFunctionRequest, _impl_.instance_id_),
  PROTOBUF_FIELD_OFFSET(::productline::CallFunctionRequest, _impl_.function_name_),
  PROTOBUF_FIELD_OFFSET(::productline::CallFunctionRequest, _impl_.params_json_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::productline::CallFunctionResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::productline::CallFunctionResponse, _impl_.result_json_),
  PROTOBUF_FIELD_OFFSET(::productline::CallFunctionResponse, _impl_.error_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::productline::GetInstanceRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::productline::GetInstanceResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::productline::GetInstanceResponse, _impl_.instance_id_),
  PROTOBUF_FIELD_OFFSET(::productline::GetInstanceResponse, _impl_.error_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::productline::InsertInstanceRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::productline::InsertInstanceRequest, _impl_.instance_id_),
  PROTOBUF_FIELD_OFFSET(::productline::InsertInstanceRequest, _impl_.instance_type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::productline::InsertInstanceResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::productline::InsertInstanceResponse, _impl_.success_),
  PROTOBUF_FIELD_OFFSET(::productline::InsertInstanceResponse, _impl_.error_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::productline::CallFunctionRequest)},
  { 9, -1, -1, sizeof(::productline::CallFunctionResponse)},
  { 17, -1, -1, sizeof(::productline::GetInstanceRequest)},
  { 23, -1, -1, sizeof(::productline::GetInstanceResponse)},
  { 31, -1, -1, sizeof(::productline::InsertInstanceRequest)},
  { 39, -1, -1, sizeof(::productline::InsertInstanceResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::productline::_CallFunctionRequest_default_instance_._instance,
  &::productline::_CallFunctionResponse_default_instance_._instance,
  &::productline::_GetInstanceRequest_default_instance_._instance,
  &::productline::_GetInstanceResponse_default_instance_._instance,
  &::productline::_InsertInstanceRequest_default_instance_._instance,
  &::productline::_InsertInstanceResponse_default_instance_._instance,
};

const char descriptor_table_protodef_productline_5fapi_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025productline_api.proto\022\013productline\"V\n\023"
  "CallFunctionRequest\022\023\n\013instance_id\030\001 \001(\004"
  "\022\025\n\rfunction_name\030\002 \001(\t\022\023\n\013params_json\030\003"
  " \001(\t\":\n\024CallFunctionResponse\022\023\n\013result_j"
  "son\030\001 \001(\t\022\r\n\005error\030\002 \001(\t\"\024\n\022GetInstanceR"
  "equest\"9\n\023GetInstanceResponse\022\023\n\013instanc"
  "e_id\030\001 \001(\004\022\r\n\005error\030\002 \001(\t\"C\n\025InsertInsta"
  "nceRequest\022\023\n\013instance_id\030\001 \001(\004\022\025\n\rinsta"
  "nce_type\030\002 \001(\t\"8\n\026InsertInstanceResponse"
  "\022\017\n\007success\030\001 \001(\010\022\r\n\005error\030\002 \001(\t2\226\002\n\022Pro"
  "ductLineService\022S\n\014CallFunction\022 .produc"
  "tline.CallFunctionRequest\032!.productline."
  "CallFunctionResponse\022P\n\013GetInstance\022\037.pr"
  "oductline.GetInstanceRequest\032 .productli"
  "ne.GetInstanceResponse\022Y\n\016InsertInstance"
  "\022\".productline.InsertInstanceRequest\032#.p"
  "roductline.InsertInstanceResponseb\006proto"
  "3"
  ;
static ::_pbi::once_flag descriptor_table_productline_5fapi_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_productline_5fapi_2eproto = {
    false, false, 681, descriptor_table_protodef_productline_5fapi_2eproto,
    "productline_api.proto",
    &descriptor_table_productline_5fapi_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_productline_5fapi_2eproto::offsets,
    file_level_metadata_productline_5fapi_2eproto, file_level_enum_descriptors_productline_5fapi_2eproto,
    file_level_service_descriptors_productline_5fapi_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_productline_5fapi_2eproto_getter() {
  return &descriptor_table_productline_5fapi_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_productline_5fapi_2eproto(&descriptor_table_productline_5fapi_2eproto);
namespace productline {

// ===================================================================

class CallFunctionRequest::_Internal {
 public:
};

CallFunctionRequest::CallFunctionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:productline.CallFunctionRequest)
}
CallFunctionRequest::CallFunctionRequest(const CallFunctionRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CallFunctionRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.function_name_){}
    , decltype(_impl_.params_json_){}
    , decltype(_impl_.instance_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.function_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.function_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_function_name().empty()) {
    _this->_impl_.function_name_.Set(from._internal_function_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.params_json_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.params_json_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_params_json().empty()) {
    _this->_impl_.params_json_.Set(from._internal_params_json(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.instance_id_ = from._impl_.instance_id_;
  // @@protoc_insertion_point(copy_constructor:productline.CallFunctionRequest)
}

inline void CallFunctionRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.function_name_){}
    , decltype(_impl_.params_json_){}
    , decltype(_impl_.instance_id_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.function_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.function_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.params_json_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.params_json_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CallFunctionRequest::~CallFunctionRequest() {
  // @@protoc_insertion_point(destructor:productline.CallFunctionRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CallFunctionRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.function_name_.Destroy();
  _impl_.params_json_.Destroy();
}

void CallFunctionRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CallFunctionRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:productline.CallFunctionRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.function_name_.ClearToEmpty();
  _impl_.params_json_.ClearToEmpty();
  _impl_.instance_id_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CallFunctionRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 instance_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.instance_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string function_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_function_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "productline.CallFunctionRequest.function_name"));
        } else
          goto handle_unusual;
        continue;
      // string params_json = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_params_json();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "productline.CallFunctionRequest.params_json"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CallFunctionRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:productline.CallFunctionRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 instance_id = 1;
  if (this->_internal_instance_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_instance_id(), target);
  }

  // string function_name = 2;
  if (!this->_internal_function_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_function_name().data(), static_cast<int>(this->_internal_function_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "productline.CallFunctionRequest.function_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_function_name(), target);
  }

  // string params_json = 3;
  if (!this->_internal_params_json().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_params_json().data(), static_cast<int>(this->_internal_params_json().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "productline.CallFunctionRequest.params_json");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_params_json(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:productline.CallFunctionRequest)
  return target;
}

size_t CallFunctionRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:productline.CallFunctionRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string function_name = 2;
  if (!this->_internal_function_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_function_name());
  }

  // string params_json = 3;
  if (!this->_internal_params_json().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_params_json());
  }

  // uint64 instance_id = 1;
  if (this->_internal_instance_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_instance_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CallFunctionRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CallFunctionRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CallFunctionRequest::GetClassData() const { return &_class_data_; }


void CallFunctionRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CallFunctionRequest*>(&to_msg);
  auto& from = static_cast<const CallFunctionRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:productline.CallFunctionRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_function_name().empty()) {
    _this->_internal_set_function_name(from._internal_function_name());
  }
  if (!from._internal_params_json().empty()) {
    _this->_internal_set_params_json(from._internal_params_json());
  }
  if (from._internal_instance_id() != 0) {
    _this->_internal_set_instance_id(from._internal_instance_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CallFunctionRequest::CopyFrom(const CallFunctionRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:productline.CallFunctionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CallFunctionRequest::IsInitialized() const {
  return true;
}

void CallFunctionRequest::InternalSwap(CallFunctionRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.function_name_, lhs_arena,
      &other->_impl_.function_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.params_json_, lhs_arena,
      &other->_impl_.params_json_, rhs_arena
  );
  swap(_impl_.instance_id_, other->_impl_.instance_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CallFunctionRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_productline_5fapi_2eproto_getter, &descriptor_table_productline_5fapi_2eproto_once,
      file_level_metadata_productline_5fapi_2eproto[0]);
}

// ===================================================================

class CallFunctionResponse::_Internal {
 public:
};

CallFunctionResponse::CallFunctionResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:productline.CallFunctionResponse)
}
CallFunctionResponse::CallFunctionResponse(const CallFunctionResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CallFunctionResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.result_json_){}
    , decltype(_impl_.error_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.result_json_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.result_json_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_result_json().empty()) {
    _this->_impl_.result_json_.Set(from._internal_result_json(), 
      _this->GetArenaForAllocation());
  }
  _impl_.error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error().empty()) {
    _this->_impl_.error_.Set(from._internal_error(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:productline.CallFunctionResponse)
}

inline void CallFunctionResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.result_json_){}
    , decltype(_impl_.error_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.result_json_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.result_json_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CallFunctionResponse::~CallFunctionResponse() {
  // @@protoc_insertion_point(destructor:productline.CallFunctionResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CallFunctionResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.result_json_.Destroy();
  _impl_.error_.Destroy();
}

void CallFunctionResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CallFunctionResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:productline.CallFunctionResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_json_.ClearToEmpty();
  _impl_.error_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CallFunctionResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string result_json = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_result_json();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "productline.CallFunctionResponse.result_json"));
        } else
          goto handle_unusual;
        continue;
      // string error = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_error();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "productline.CallFunctionResponse.error"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CallFunctionResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:productline.CallFunctionResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string result_json = 1;
  if (!this->_internal_result_json().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_result_json().data(), static_cast<int>(this->_internal_result_json().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "productline.CallFunctionResponse.result_json");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_result_json(), target);
  }

  // string error = 2;
  if (!this->_internal_error().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error().data(), static_cast<int>(this->_internal_error().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "productline.CallFunctionResponse.error");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_error(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:productline.CallFunctionResponse)
  return target;
}

size_t CallFunctionResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:productline.CallFunctionResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string result_json = 1;
  if (!this->_internal_result_json().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_result_json());
  }

  // string error = 2;
  if (!this->_internal_error().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CallFunctionResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CallFunctionResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CallFunctionResponse::GetClassData() const { return &_class_data_; }


void CallFunctionResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CallFunctionResponse*>(&to_msg);
  auto& from = static_cast<const CallFunctionResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:productline.CallFunctionResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_result_json().empty()) {
    _this->_internal_set_result_json(from._internal_result_json());
  }
  if (!from._internal_error().empty()) {
    _this->_internal_set_error(from._internal_error());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CallFunctionResponse::CopyFrom(const CallFunctionResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:productline.CallFunctionResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CallFunctionResponse::IsInitialized() const {
  return true;
}

void CallFunctionResponse::InternalSwap(CallFunctionResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.result_json_, lhs_arena,
      &other->_impl_.result_json_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_, lhs_arena,
      &other->_impl_.error_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata CallFunctionResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_productline_5fapi_2eproto_getter, &descriptor_table_productline_5fapi_2eproto_once,
      file_level_metadata_productline_5fapi_2eproto[1]);
}

// ===================================================================

class GetInstanceRequest::_Internal {
 public:
};

GetInstanceRequest::GetInstanceRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:productline.GetInstanceRequest)
}
GetInstanceRequest::GetInstanceRequest(const GetInstanceRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  GetInstanceRequest* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:productline.GetInstanceRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetInstanceRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetInstanceRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata GetInstanceRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_productline_5fapi_2eproto_getter, &descriptor_table_productline_5fapi_2eproto_once,
      file_level_metadata_productline_5fapi_2eproto[2]);
}

// ===================================================================

class GetInstanceResponse::_Internal {
 public:
};

GetInstanceResponse::GetInstanceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:productline.GetInstanceResponse)
}
GetInstanceResponse::GetInstanceResponse(const GetInstanceResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetInstanceResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.error_){}
    , decltype(_impl_.instance_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error().empty()) {
    _this->_impl_.error_.Set(from._internal_error(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.instance_id_ = from._impl_.instance_id_;
  // @@protoc_insertion_point(copy_constructor:productline.GetInstanceResponse)
}

inline void GetInstanceResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.error_){}
    , decltype(_impl_.instance_id_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

GetInstanceResponse::~GetInstanceResponse() {
  // @@protoc_insertion_point(destructor:productline.GetInstanceResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetInstanceResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.error_.Destroy();
}

void GetInstanceResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetInstanceResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:productline.GetInstanceResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_.ClearToEmpty();
  _impl_.instance_id_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetInstanceResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 instance_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.instance_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string error = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_error();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "productline.GetInstanceResponse.error"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetInstanceResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:productline.GetInstanceResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 instance_id = 1;
  if (this->_internal_instance_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_instance_id(), target);
  }

  // string error = 2;
  if (!this->_internal_error().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error().data(), static_cast<int>(this->_internal_error().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "productline.GetInstanceResponse.error");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_error(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:productline.GetInstanceResponse)
  return target;
}

size_t GetInstanceResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:productline.GetInstanceResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string error = 2;
  if (!this->_internal_error().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error());
  }

  // uint64 instance_id = 1;
  if (this->_internal_instance_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_instance_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetInstanceResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetInstanceResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetInstanceResponse::GetClassData() const { return &_class_data_; }


void GetInstanceResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetInstanceResponse*>(&to_msg);
  auto& from = static_cast<const GetInstanceResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:productline.GetInstanceResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_error().empty()) {
    _this->_internal_set_error(from._internal_error());
  }
  if (from._internal_instance_id() != 0) {
    _this->_internal_set_instance_id(from._internal_instance_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetInstanceResponse::CopyFrom(const GetInstanceResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:productline.GetInstanceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetInstanceResponse::IsInitialized() const {
  return true;
}

void GetInstanceResponse::InternalSwap(GetInstanceResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_, lhs_arena,
      &other->_impl_.error_, rhs_arena
  );
  swap(_impl_.instance_id_, other->_impl_.instance_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetInstanceResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_productline_5fapi_2eproto_getter, &descriptor_table_productline_5fapi_2eproto_once,
      file_level_metadata_productline_5fapi_2eproto[3]);
}

// ===================================================================

class InsertInstanceRequest::_Internal {
 public:
};

InsertInstanceRequest::InsertInstanceRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:productline.InsertInstanceRequest)
}
InsertInstanceRequest::InsertInstanceRequest(const InsertInstanceRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  InsertInstanceRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.instance_type_){}
    , decltype(_impl_.instance_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.instance_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.instance_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_instance_type().empty()) {
    _this->_impl_.instance_type_.Set(from._internal_instance_type(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.instance_id_ = from._impl_.instance_id_;
  // @@protoc_insertion_point(copy_constructor:productline.InsertInstanceRequest)
}

inline void InsertInstanceRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.instance_type_){}
    , decltype(_impl_.instance_id_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.instance_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.instance_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

InsertInstanceRequest::~InsertInstanceRequest() {
  // @@protoc_insertion_point(destructor:productline.InsertInstanceRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InsertInstanceRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.instance_type_.Destroy();
}

void InsertInstanceRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void InsertInstanceRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:productline.InsertInstanceRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.instance_type_.ClearToEmpty();
  _impl_.instance_id_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InsertInstanceRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 instance_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.instance_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string instance_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_instance_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "productline.InsertInstanceRequest.instance_type"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InsertInstanceRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:productline.InsertInstanceRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 instance_id = 1;
  if (this->_internal_instance_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_instance_id(), target);
  }

  // string instance_type = 2;
  if (!this->_internal_instance_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_instance_type().data(), static_cast<int>(this->_internal_instance_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "productline.InsertInstanceRequest.instance_type");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_instance_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:productline.InsertInstanceRequest)
  return target;
}

size_t InsertInstanceRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:productline.InsertInstanceRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string instance_type = 2;
  if (!this->_internal_instance_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_instance_type());
  }

  // uint64 instance_id = 1;
  if (this->_internal_instance_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_instance_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InsertInstanceRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    InsertInstanceRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InsertInstanceRequest::GetClassData() const { return &_class_data_; }


void InsertInstanceRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<InsertInstanceRequest*>(&to_msg);
  auto& from = static_cast<const InsertInstanceRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:productline.InsertInstanceRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_instance_type().empty()) {
    _this->_internal_set_instance_type(from._internal_instance_type());
  }
  if (from._internal_instance_id() != 0) {
    _this->_internal_set_instance_id(from._internal_instance_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InsertInstanceRequest::CopyFrom(const InsertInstanceRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:productline.InsertInstanceRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InsertInstanceRequest::IsInitialized() const {
  return true;
}

void InsertInstanceRequest::InternalSwap(InsertInstanceRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.instance_type_, lhs_arena,
      &other->_impl_.instance_type_, rhs_arena
  );
  swap(_impl_.instance_id_, other->_impl_.instance_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata InsertInstanceRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_productline_5fapi_2eproto_getter, &descriptor_table_productline_5fapi_2eproto_once,
      file_level_metadata_productline_5fapi_2eproto[4]);
}

// ===================================================================

class InsertInstanceResponse::_Internal {
 public:
};

InsertInstanceResponse::InsertInstanceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:productline.InsertInstanceResponse)
}
InsertInstanceResponse::InsertInstanceResponse(const InsertInstanceResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  InsertInstanceResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.error_){}
    , decltype(_impl_.success_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error().empty()) {
    _this->_impl_.error_.Set(from._internal_error(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.success_ = from._impl_.success_;
  // @@protoc_insertion_point(copy_constructor:productline.InsertInstanceResponse)
}

inline void InsertInstanceResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.error_){}
    , decltype(_impl_.success_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

InsertInstanceResponse::~InsertInstanceResponse() {
  // @@protoc_insertion_point(destructor:productline.InsertInstanceResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InsertInstanceResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.error_.Destroy();
}

void InsertInstanceResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void InsertInstanceResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:productline.InsertInstanceResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_.ClearToEmpty();
  _impl_.success_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InsertInstanceResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string error = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_error();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "productline.InsertInstanceResponse.error"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InsertInstanceResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:productline.InsertInstanceResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  // string error = 2;
  if (!this->_internal_error().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error().data(), static_cast<int>(this->_internal_error().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "productline.InsertInstanceResponse.error");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_error(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:productline.InsertInstanceResponse)
  return target;
}

size_t InsertInstanceResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:productline.InsertInstanceResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string error = 2;
  if (!this->_internal_error().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error());
  }

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InsertInstanceResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    InsertInstanceResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InsertInstanceResponse::GetClassData() const { return &_class_data_; }


void InsertInstanceResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<InsertInstanceResponse*>(&to_msg);
  auto& from = static_cast<const InsertInstanceResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:productline.InsertInstanceResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_error().empty()) {
    _this->_internal_set_error(from._internal_error());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InsertInstanceResponse::CopyFrom(const InsertInstanceResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:productline.InsertInstanceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InsertInstanceResponse::IsInitialized() const {
  return true;
}

void InsertInstanceResponse::InternalSwap(InsertInstanceResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_, lhs_arena,
      &other->_impl_.error_, rhs_arena
  );
  swap(_impl_.success_, other->_impl_.success_);
}

::PROTOBUF_NAMESPACE_ID::Metadata InsertInstanceResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_productline_5fapi_2eproto_getter, &descriptor_table_productline_5fapi_2eproto_once,
      file_level_metadata_productline_5fapi_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace productline
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::productline::CallFunctionRequest*
Arena::CreateMaybeMessage< ::productline::CallFunctionRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::productline::CallFunctionRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::productline::CallFunctionResponse*
Arena::CreateMaybeMessage< ::productline::CallFunctionResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::productline::CallFunctionResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::productline::GetInstanceRequest*
Arena::CreateMaybeMessage< ::productline::GetInstanceRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::productline::GetInstanceRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::productline::GetInstanceResponse*
Arena::CreateMaybeMessage< ::productline::GetInstanceResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::productline::GetInstanceResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::productline::InsertInstanceRequest*
Arena::CreateMaybeMessage< ::productline::InsertInstanceRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::productline::InsertInstanceRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::productline::InsertInstanceResponse*
Arena::CreateMaybeMessage< ::productline::InsertInstanceResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::productline::InsertInstanceResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
