// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: productline_api.proto

#include "productline_api.pb.h"
#include "productline_api.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace productline {

static const char* ProductLineService_method_names[] = {
  "/productline.ProductLineService/CallFunction",
  "/productline.ProductLineService/GetInstance",
  "/productline.ProductLineService/InsertInstance",
};

std::unique_ptr< ProductLineService::Stub> ProductLineService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ProductLineService::Stub> stub(new ProductLineService::Stub(channel, options));
  return stub;
}

ProductLineService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CallFunction_(ProductLineService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetInstance_(ProductLineService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_InsertInstance_(ProductLineService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ProductLineService::Stub::CallFunction(::grpc::ClientContext* context, const ::productline::CallFunctionRequest& request, ::productline::CallFunctionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::productline::CallFunctionRequest, ::productline::CallFunctionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CallFunction_, context, request, response);
}

void ProductLineService::Stub::async::CallFunction(::grpc::ClientContext* context, const ::productline::CallFunctionRequest* request, ::productline::CallFunctionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::productline::CallFunctionRequest, ::productline::CallFunctionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CallFunction_, context, request, response, std::move(f));
}

void ProductLineService::Stub::async::CallFunction(::grpc::ClientContext* context, const ::productline::CallFunctionRequest* request, ::productline::CallFunctionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CallFunction_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::productline::CallFunctionResponse>* ProductLineService::Stub::PrepareAsyncCallFunctionRaw(::grpc::ClientContext* context, const ::productline::CallFunctionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::productline::CallFunctionResponse, ::productline::CallFunctionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CallFunction_, context, request);
}

::grpc::ClientAsyncResponseReader< ::productline::CallFunctionResponse>* ProductLineService::Stub::AsyncCallFunctionRaw(::grpc::ClientContext* context, const ::productline::CallFunctionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCallFunctionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ProductLineService::Stub::GetInstance(::grpc::ClientContext* context, const ::productline::GetInstanceRequest& request, ::productline::GetInstanceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::productline::GetInstanceRequest, ::productline::GetInstanceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetInstance_, context, request, response);
}

void ProductLineService::Stub::async::GetInstance(::grpc::ClientContext* context, const ::productline::GetInstanceRequest* request, ::productline::GetInstanceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::productline::GetInstanceRequest, ::productline::GetInstanceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetInstance_, context, request, response, std::move(f));
}

void ProductLineService::Stub::async::GetInstance(::grpc::ClientContext* context, const ::productline::GetInstanceRequest* request, ::productline::GetInstanceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetInstance_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::productline::GetInstanceResponse>* ProductLineService::Stub::PrepareAsyncGetInstanceRaw(::grpc::ClientContext* context, const ::productline::GetInstanceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::productline::GetInstanceResponse, ::productline::GetInstanceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetInstance_, context, request);
}

::grpc::ClientAsyncResponseReader< ::productline::GetInstanceResponse>* ProductLineService::Stub::AsyncGetInstanceRaw(::grpc::ClientContext* context, const ::productline::GetInstanceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetInstanceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ProductLineService::Stub::InsertInstance(::grpc::ClientContext* context, const ::productline::InsertInstanceRequest& request, ::productline::InsertInstanceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::productline::InsertInstanceRequest, ::productline::InsertInstanceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_InsertInstance_, context, request, response);
}

void ProductLineService::Stub::async::InsertInstance(::grpc::ClientContext* context, const ::productline::InsertInstanceRequest* request, ::productline::InsertInstanceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::productline::InsertInstanceRequest, ::productline::InsertInstanceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InsertInstance_, context, request, response, std::move(f));
}

void ProductLineService::Stub::async::InsertInstance(::grpc::ClientContext* context, const ::productline::InsertInstanceRequest* request, ::productline::InsertInstanceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InsertInstance_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::productline::InsertInstanceResponse>* ProductLineService::Stub::PrepareAsyncInsertInstanceRaw(::grpc::ClientContext* context, const ::productline::InsertInstanceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::productline::InsertInstanceResponse, ::productline::InsertInstanceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_InsertInstance_, context, request);
}

::grpc::ClientAsyncResponseReader< ::productline::InsertInstanceResponse>* ProductLineService::Stub::AsyncInsertInstanceRaw(::grpc::ClientContext* context, const ::productline::InsertInstanceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInsertInstanceRaw(context, request, cq);
  result->StartCall();
  return result;
}

ProductLineService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProductLineService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProductLineService::Service, ::productline::CallFunctionRequest, ::productline::CallFunctionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProductLineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::productline::CallFunctionRequest* req,
             ::productline::CallFunctionResponse* resp) {
               return service->CallFunction(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProductLineService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProductLineService::Service, ::productline::GetInstanceRequest, ::productline::GetInstanceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProductLineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::productline::GetInstanceRequest* req,
             ::productline::GetInstanceResponse* resp) {
               return service->GetInstance(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProductLineService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProductLineService::Service, ::productline::InsertInstanceRequest, ::productline::InsertInstanceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProductLineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::productline::InsertInstanceRequest* req,
             ::productline::InsertInstanceResponse* resp) {
               return service->InsertInstance(ctx, req, resp);
             }, this)));
}

ProductLineService::Service::~Service() {
}

::grpc::Status ProductLineService::Service::CallFunction(::grpc::ServerContext* context, const ::productline::CallFunctionRequest* request, ::productline::CallFunctionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ProductLineService::Service::GetInstance(::grpc::ServerContext* context, const ::productline::GetInstanceRequest* request, ::productline::GetInstanceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ProductLineService::Service::InsertInstance(::grpc::ServerContext* context, const ::productline::InsertInstanceRequest* request, ::productline::InsertInstanceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace productline

