// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: productline_api.proto
#ifndef GRPC_productline_5fapi_2eproto__INCLUDED
#define GRPC_productline_5fapi_2eproto__INCLUDED

#include "productline_api.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace productline {

// gRPC service definition for the Product Line API
class ProductLineService final {
 public:
  static constexpr char const* service_full_name() {
    return "productline.ProductLineService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Call a function on a specific instance
    virtual ::grpc::Status CallFunction(::grpc::ClientContext* context, const ::productline::CallFunctionRequest& request, ::productline::CallFunctionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::productline::CallFunctionResponse>> AsyncCallFunction(::grpc::ClientContext* context, const ::productline::CallFunctionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::productline::CallFunctionResponse>>(AsyncCallFunctionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::productline::CallFunctionResponse>> PrepareAsyncCallFunction(::grpc::ClientContext* context, const ::productline::CallFunctionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::productline::CallFunctionResponse>>(PrepareAsyncCallFunctionRaw(context, request, cq));
    }
    // Get the main instance
    virtual ::grpc::Status GetInstance(::grpc::ClientContext* context, const ::productline::GetInstanceRequest& request, ::productline::GetInstanceResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::productline::GetInstanceResponse>> AsyncGetInstance(::grpc::ClientContext* context, const ::productline::GetInstanceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::productline::GetInstanceResponse>>(AsyncGetInstanceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::productline::GetInstanceResponse>> PrepareAsyncGetInstance(::grpc::ClientContext* context, const ::productline::GetInstanceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::productline::GetInstanceResponse>>(PrepareAsyncGetInstanceRaw(context, request, cq));
    }
    // Insert a new instance (for management purposes)
    virtual ::grpc::Status InsertInstance(::grpc::ClientContext* context, const ::productline::InsertInstanceRequest& request, ::productline::InsertInstanceResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::productline::InsertInstanceResponse>> AsyncInsertInstance(::grpc::ClientContext* context, const ::productline::InsertInstanceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::productline::InsertInstanceResponse>>(AsyncInsertInstanceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::productline::InsertInstanceResponse>> PrepareAsyncInsertInstance(::grpc::ClientContext* context, const ::productline::InsertInstanceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::productline::InsertInstanceResponse>>(PrepareAsyncInsertInstanceRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Call a function on a specific instance
      virtual void CallFunction(::grpc::ClientContext* context, const ::productline::CallFunctionRequest* request, ::productline::CallFunctionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CallFunction(::grpc::ClientContext* context, const ::productline::CallFunctionRequest* request, ::productline::CallFunctionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Get the main instance
      virtual void GetInstance(::grpc::ClientContext* context, const ::productline::GetInstanceRequest* request, ::productline::GetInstanceResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetInstance(::grpc::ClientContext* context, const ::productline::GetInstanceRequest* request, ::productline::GetInstanceResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Insert a new instance (for management purposes)
      virtual void InsertInstance(::grpc::ClientContext* context, const ::productline::InsertInstanceRequest* request, ::productline::InsertInstanceResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void InsertInstance(::grpc::ClientContext* context, const ::productline::InsertInstanceRequest* request, ::productline::InsertInstanceResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::productline::CallFunctionResponse>* AsyncCallFunctionRaw(::grpc::ClientContext* context, const ::productline::CallFunctionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::productline::CallFunctionResponse>* PrepareAsyncCallFunctionRaw(::grpc::ClientContext* context, const ::productline::CallFunctionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::productline::GetInstanceResponse>* AsyncGetInstanceRaw(::grpc::ClientContext* context, const ::productline::GetInstanceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::productline::GetInstanceResponse>* PrepareAsyncGetInstanceRaw(::grpc::ClientContext* context, const ::productline::GetInstanceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::productline::InsertInstanceResponse>* AsyncInsertInstanceRaw(::grpc::ClientContext* context, const ::productline::InsertInstanceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::productline::InsertInstanceResponse>* PrepareAsyncInsertInstanceRaw(::grpc::ClientContext* context, const ::productline::InsertInstanceRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CallFunction(::grpc::ClientContext* context, const ::productline::CallFunctionRequest& request, ::productline::CallFunctionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::productline::CallFunctionResponse>> AsyncCallFunction(::grpc::ClientContext* context, const ::productline::CallFunctionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::productline::CallFunctionResponse>>(AsyncCallFunctionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::productline::CallFunctionResponse>> PrepareAsyncCallFunction(::grpc::ClientContext* context, const ::productline::CallFunctionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::productline::CallFunctionResponse>>(PrepareAsyncCallFunctionRaw(context, request, cq));
    }
    ::grpc::Status GetInstance(::grpc::ClientContext* context, const ::productline::GetInstanceRequest& request, ::productline::GetInstanceResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::productline::GetInstanceResponse>> AsyncGetInstance(::grpc::ClientContext* context, const ::productline::GetInstanceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::productline::GetInstanceResponse>>(AsyncGetInstanceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::productline::GetInstanceResponse>> PrepareAsyncGetInstance(::grpc::ClientContext* context, const ::productline::GetInstanceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::productline::GetInstanceResponse>>(PrepareAsyncGetInstanceRaw(context, request, cq));
    }
    ::grpc::Status InsertInstance(::grpc::ClientContext* context, const ::productline::InsertInstanceRequest& request, ::productline::InsertInstanceResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::productline::InsertInstanceResponse>> AsyncInsertInstance(::grpc::ClientContext* context, const ::productline::InsertInstanceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::productline::InsertInstanceResponse>>(AsyncInsertInstanceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::productline::InsertInstanceResponse>> PrepareAsyncInsertInstance(::grpc::ClientContext* context, const ::productline::InsertInstanceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::productline::InsertInstanceResponse>>(PrepareAsyncInsertInstanceRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CallFunction(::grpc::ClientContext* context, const ::productline::CallFunctionRequest* request, ::productline::CallFunctionResponse* response, std::function<void(::grpc::Status)>) override;
      void CallFunction(::grpc::ClientContext* context, const ::productline::CallFunctionRequest* request, ::productline::CallFunctionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetInstance(::grpc::ClientContext* context, const ::productline::GetInstanceRequest* request, ::productline::GetInstanceResponse* response, std::function<void(::grpc::Status)>) override;
      void GetInstance(::grpc::ClientContext* context, const ::productline::GetInstanceRequest* request, ::productline::GetInstanceResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void InsertInstance(::grpc::ClientContext* context, const ::productline::InsertInstanceRequest* request, ::productline::InsertInstanceResponse* response, std::function<void(::grpc::Status)>) override;
      void InsertInstance(::grpc::ClientContext* context, const ::productline::InsertInstanceRequest* request, ::productline::InsertInstanceResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::productline::CallFunctionResponse>* AsyncCallFunctionRaw(::grpc::ClientContext* context, const ::productline::CallFunctionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::productline::CallFunctionResponse>* PrepareAsyncCallFunctionRaw(::grpc::ClientContext* context, const ::productline::CallFunctionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::productline::GetInstanceResponse>* AsyncGetInstanceRaw(::grpc::ClientContext* context, const ::productline::GetInstanceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::productline::GetInstanceResponse>* PrepareAsyncGetInstanceRaw(::grpc::ClientContext* context, const ::productline::GetInstanceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::productline::InsertInstanceResponse>* AsyncInsertInstanceRaw(::grpc::ClientContext* context, const ::productline::InsertInstanceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::productline::InsertInstanceResponse>* PrepareAsyncInsertInstanceRaw(::grpc::ClientContext* context, const ::productline::InsertInstanceRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CallFunction_;
    const ::grpc::internal::RpcMethod rpcmethod_GetInstance_;
    const ::grpc::internal::RpcMethod rpcmethod_InsertInstance_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Call a function on a specific instance
    virtual ::grpc::Status CallFunction(::grpc::ServerContext* context, const ::productline::CallFunctionRequest* request, ::productline::CallFunctionResponse* response);
    // Get the main instance
    virtual ::grpc::Status GetInstance(::grpc::ServerContext* context, const ::productline::GetInstanceRequest* request, ::productline::GetInstanceResponse* response);
    // Insert a new instance (for management purposes)
    virtual ::grpc::Status InsertInstance(::grpc::ServerContext* context, const ::productline::InsertInstanceRequest* request, ::productline::InsertInstanceResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CallFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CallFunction() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CallFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallFunction(::grpc::ServerContext* /*context*/, const ::productline::CallFunctionRequest* /*request*/, ::productline::CallFunctionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCallFunction(::grpc::ServerContext* context, ::productline::CallFunctionRequest* request, ::grpc::ServerAsyncResponseWriter< ::productline::CallFunctionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetInstance : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetInstance() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetInstance() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInstance(::grpc::ServerContext* /*context*/, const ::productline::GetInstanceRequest* /*request*/, ::productline::GetInstanceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetInstance(::grpc::ServerContext* context, ::productline::GetInstanceRequest* request, ::grpc::ServerAsyncResponseWriter< ::productline::GetInstanceResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_InsertInstance : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_InsertInstance() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_InsertInstance() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InsertInstance(::grpc::ServerContext* /*context*/, const ::productline::InsertInstanceRequest* /*request*/, ::productline::InsertInstanceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInsertInstance(::grpc::ServerContext* context, ::productline::InsertInstanceRequest* request, ::grpc::ServerAsyncResponseWriter< ::productline::InsertInstanceResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CallFunction<WithAsyncMethod_GetInstance<WithAsyncMethod_InsertInstance<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CallFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CallFunction() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::productline::CallFunctionRequest, ::productline::CallFunctionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::productline::CallFunctionRequest* request, ::productline::CallFunctionResponse* response) { return this->CallFunction(context, request, response); }));}
    void SetMessageAllocatorFor_CallFunction(
        ::grpc::MessageAllocator< ::productline::CallFunctionRequest, ::productline::CallFunctionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::productline::CallFunctionRequest, ::productline::CallFunctionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CallFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallFunction(::grpc::ServerContext* /*context*/, const ::productline::CallFunctionRequest* /*request*/, ::productline::CallFunctionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CallFunction(
      ::grpc::CallbackServerContext* /*context*/, const ::productline::CallFunctionRequest* /*request*/, ::productline::CallFunctionResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetInstance : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetInstance() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::productline::GetInstanceRequest, ::productline::GetInstanceResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::productline::GetInstanceRequest* request, ::productline::GetInstanceResponse* response) { return this->GetInstance(context, request, response); }));}
    void SetMessageAllocatorFor_GetInstance(
        ::grpc::MessageAllocator< ::productline::GetInstanceRequest, ::productline::GetInstanceResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::productline::GetInstanceRequest, ::productline::GetInstanceResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetInstance() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInstance(::grpc::ServerContext* /*context*/, const ::productline::GetInstanceRequest* /*request*/, ::productline::GetInstanceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetInstance(
      ::grpc::CallbackServerContext* /*context*/, const ::productline::GetInstanceRequest* /*request*/, ::productline::GetInstanceResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_InsertInstance : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_InsertInstance() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::productline::InsertInstanceRequest, ::productline::InsertInstanceResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::productline::InsertInstanceRequest* request, ::productline::InsertInstanceResponse* response) { return this->InsertInstance(context, request, response); }));}
    void SetMessageAllocatorFor_InsertInstance(
        ::grpc::MessageAllocator< ::productline::InsertInstanceRequest, ::productline::InsertInstanceResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::productline::InsertInstanceRequest, ::productline::InsertInstanceResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_InsertInstance() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InsertInstance(::grpc::ServerContext* /*context*/, const ::productline::InsertInstanceRequest* /*request*/, ::productline::InsertInstanceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* InsertInstance(
      ::grpc::CallbackServerContext* /*context*/, const ::productline::InsertInstanceRequest* /*request*/, ::productline::InsertInstanceResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CallFunction<WithCallbackMethod_GetInstance<WithCallbackMethod_InsertInstance<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CallFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CallFunction() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CallFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallFunction(::grpc::ServerContext* /*context*/, const ::productline::CallFunctionRequest* /*request*/, ::productline::CallFunctionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetInstance : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetInstance() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetInstance() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInstance(::grpc::ServerContext* /*context*/, const ::productline::GetInstanceRequest* /*request*/, ::productline::GetInstanceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_InsertInstance : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_InsertInstance() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_InsertInstance() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InsertInstance(::grpc::ServerContext* /*context*/, const ::productline::InsertInstanceRequest* /*request*/, ::productline::InsertInstanceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CallFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CallFunction() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CallFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallFunction(::grpc::ServerContext* /*context*/, const ::productline::CallFunctionRequest* /*request*/, ::productline::CallFunctionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCallFunction(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetInstance : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetInstance() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetInstance() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInstance(::grpc::ServerContext* /*context*/, const ::productline::GetInstanceRequest* /*request*/, ::productline::GetInstanceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetInstance(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_InsertInstance : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_InsertInstance() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_InsertInstance() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InsertInstance(::grpc::ServerContext* /*context*/, const ::productline::InsertInstanceRequest* /*request*/, ::productline::InsertInstanceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInsertInstance(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CallFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CallFunction() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CallFunction(context, request, response); }));
    }
    ~WithRawCallbackMethod_CallFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CallFunction(::grpc::ServerContext* /*context*/, const ::productline::CallFunctionRequest* /*request*/, ::productline::CallFunctionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CallFunction(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetInstance : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetInstance() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetInstance(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetInstance() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInstance(::grpc::ServerContext* /*context*/, const ::productline::GetInstanceRequest* /*request*/, ::productline::GetInstanceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetInstance(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_InsertInstance : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_InsertInstance() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->InsertInstance(context, request, response); }));
    }
    ~WithRawCallbackMethod_InsertInstance() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status InsertInstance(::grpc::ServerContext* /*context*/, const ::productline::InsertInstanceRequest* /*request*/, ::productline::InsertInstanceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* InsertInstance(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CallFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CallFunction() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::productline::CallFunctionRequest, ::productline::CallFunctionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::productline::CallFunctionRequest, ::productline::CallFunctionResponse>* streamer) {
                       return this->StreamedCallFunction(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CallFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CallFunction(::grpc::ServerContext* /*context*/, const ::productline::CallFunctionRequest* /*request*/, ::productline::CallFunctionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCallFunction(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::productline::CallFunctionRequest,::productline::CallFunctionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetInstance : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetInstance() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::productline::GetInstanceRequest, ::productline::GetInstanceResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::productline::GetInstanceRequest, ::productline::GetInstanceResponse>* streamer) {
                       return this->StreamedGetInstance(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetInstance() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetInstance(::grpc::ServerContext* /*context*/, const ::productline::GetInstanceRequest* /*request*/, ::productline::GetInstanceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetInstance(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::productline::GetInstanceRequest,::productline::GetInstanceResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_InsertInstance : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_InsertInstance() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::productline::InsertInstanceRequest, ::productline::InsertInstanceResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::productline::InsertInstanceRequest, ::productline::InsertInstanceResponse>* streamer) {
                       return this->StreamedInsertInstance(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_InsertInstance() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status InsertInstance(::grpc::ServerContext* /*context*/, const ::productline::InsertInstanceRequest* /*request*/, ::productline::InsertInstanceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedInsertInstance(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::productline::InsertInstanceRequest,::productline::InsertInstanceResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CallFunction<WithStreamedUnaryMethod_GetInstance<WithStreamedUnaryMethod_InsertInstance<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CallFunction<WithStreamedUnaryMethod_GetInstance<WithStreamedUnaryMethod_InsertInstance<Service > > > StreamedService;
};

}  // namespace productline


#endif  // GRPC_productline_5fapi_2eproto__INCLUDED
