#ifndef UNIQUEASSET2_GLOBAL_H
#define UNIQUEASSET2_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNIQUEASSET2_LIBRARY)
#define UNIQUEASSET2_EXPORT Q_DECL_EXPORT
#else
#define UNIQUEASSET2_EXPORT Q_DECL_IMPORT
#endif

#endif // UNIQUEASSET2_GLOBAL_H
