
list(APPEND HEADERS UniqueAsset3/tst_uniqueasset3.h)
list(APPEND SOURCES UniqueAsset3/tst_uniqueasset3.cpp)

if(MSVC)
    if(CMAKE_BUILD_TYPE STREQUAL "Release")
        list(APPEND LIBS -L${CMAKE_CURRENT_BINARY_DIR}/../UniqueAsset3/release/ -lUniqueAsset3)
        list(APPEND ASSETS_LIB_PATH ${CMAKE_CURRENT_BINARY_DIR}/../UniqueAsset3/release/libUniqueAsset3.dll)
    else()
        list(APPEND LIBS -L${CMAKE_CURRENT_BINARY_DIR}/../UniqueAsset3/debug/ -lUniqueAsset3)
        list(APPEND ASSETS_LIB_PATH ${CMAKE_CURRENT_BINARY_DIR}/../UniqueAsset3/debug/libUniqueAsset3.dll)
    endif()
else()
    list(APPEND LIBS -L${CMAKE_CURRENT_BINARY_DIR}/../UniqueAsset3/ -lUniqueAsset3)
    list(APPEND ASSETS_LIB_PATH ${CMAKE_CURRENT_BINARY_DIR}/../UniqueAsset3/libUniqueAsset3.dll)
endif()

list(APPEND DEFINES -DUAsset3)
list(APPEND ASSETS_HEADER_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../UniqueAsset3)
list(APPEND Dependencies UniqueAsset3)
